<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE cmsmsinstall [
 <!ELEMENT dtdversion (#PCDATA)>
 <!ELEMENT designs (design+)>
 <!ELEMENT design (id,name,description?,dflt?)>
 <!ELEMENT id (#PCDATA)>
 <!ELEMENT name (#PCDATA)>
 <!ELEMENT description (#PCDATA)>
 <!ELEMENT dflt (#PCDATA)>
 <!ELEMENT stylesheets (stylesheet+)>
 <!ELEMENT stylesheet (id,name,description?,media_type?,content)>
 <!ELEMENT media_type (#PCDATA)>
 <!ELEMENT content (#PCDATA)>
 <!ELEMENT designstyles (designcss+)>
 <!ELEMENT designcss (design_id,css_id,item_order)>
 <!ELEMENT design_id (#PCDATA)>
 <!ELEMENT css_id (#PCDATA)>
 <!ELEMENT item_order (#PCDATA)>
 <!ELEMENT tpltypes (tpltype+)>
 <!ELEMENT tpltype (id,name,description?,originator,one_only?,has_dflt?,dflt_contents?,requires_contentblocks?,lang_cb?,dflt_content_cb?,help_content_cb?)>
 <!ELEMENT originator (#PCDATA)>
 <!ELEMENT one_only (#PCDATA)>
 <!ELEMENT has_dflt (#PCDATA)>
 <!ELEMENT dflt_contents (#PCDATA)>
 <!ELEMENT requires_contentblocks (#PCDATA)>
 <!ELEMENT lang_cb (#PCDATA)>
 <!ELEMENT dflt_content_cb (#PCDATA)>
 <!ELEMENT help_content_cb (#PCDATA)>
 <!ELEMENT categories (category+)>
 <!ELEMENT category (id,name,description?,item_order?)>
 <!ELEMENT templates (template)>
 <!ELEMENT template (id,name,description?,type_id,category_id?,type_dflt?,content)>
 <!ELEMENT type_id (#PCDATA)>
 <!ELEMENT category_id (#PCDATA)>
 <!ELEMENT type_dflt (#PCDATA)>
 <!ELEMENT designtemplates (designtpl+)>
 <!ELEMENT designtpl (design_id,tpl_id,tpl_order?)>
 <!ELEMENT tpl_id (#PCDATA)>
 <!ELEMENT tpl_order (#PCDATA)>
 <!ELEMENT categorytemplates (cattpl+)>
 <!ELEMENT cattpl (category_id,tpl_id,tpl_order?)>
 <!ELEMENT pages (page+)>
 <!ELEMENT page (content_id,content_name,content_alias?,type,template_id,parent_id,active?,default_content?,show_in_menu?,menu_text,cachable?)>
 <!ELEMENT content_id (#PCDATA)>
 <!ELEMENT content_name (#PCDATA)>
 <!ELEMENT content_alias (#PCDATA)>
 <!ELEMENT type (#PCDATA)>
 <!ELEMENT template_id (#PCDATA)>
 <!ELEMENT parent_id (#PCDATA)>
 <!ELEMENT active (#PCDATA)>
 <!ELEMENT default_content (#PCDATA)>
 <!ELEMENT show_in_menu (#PCDATA)>
 <!ELEMENT menu_text (#PCDATA)>
 <!ELEMENT cacheable (#PCDATA)>
 <!ELEMENT properties (property+)>
 <!ELEMENT property (content_id,prop_name,content)>
 <!ELEMENT prop_name (#PCDATA)>
 <!ELEMENT files (sourcedir?,file+)>
 <!ELEMENT file (name,topath,(frompath|embedded),content?)>
 <!ELEMENT topath (#PCDATA)>
 <!ELEMENT frompath (#PCDATA)>
 <!ELEMENT embedded (#PCDATA)>
 <!ELEMENT userplugins (sourcedir?,file+)>
 <!ELEMENT file (name,(frompath|embedded),content?)>
 ]>
<cmsmsinstall>
	<dtdversion>0.6</dtdversion>

	<designs>
		<design>
			<id>1</id>
			<name>Simplex</name>
			<description>Simplex Template is a HTML5 based theme, introduced with CMSMS 1.11 release and improved with 2.0 release.&#13;
Purpose of this theme is to demonstrate what and how can be done with CMSMS Templates using HTML5 and responsive CSS for a better mobile experience.&#13;
All Smarty templates which are used by Simplex Theme are prefix with &quot;Simplex&quot;, therefore be careful when renaming or deleting these templates.&#13;
Theme itself is using jQuery, the functions JavaScript file is minified, in case you wish to change some JavaScript functions, refer to /uploads/simplex/js/functions.js file and replace functions.min.js file.</description>
			<dflt>1</dflt>
		</design>
	</designs>
	<stylesheets>
		<stylesheet>
			<id>1</id>
			<name>Simplex Core</name>
			<description>Simplex Theme core Stylesheet, containing 12 column grid system and HTML5 resets (normalize.css)</description>
			<media_type>screen</media_type>
			<content><![CDATA[[[strip]]

[[* /*! normalize.css v2.1.3 | MIT License | git.io/normalize */ *]]

[[* /* ==========================================================================
 HTML5 display definitions
 ========================================================================== */ *]]

[[* /**
 * Correct `block` display not defined in IE 8/9.
 */ *]]

article, aside, details, figcaption, figure, footer, header, hgroup, main, nav, section, summary {
	display: block;
}

[[* /**
 * Correct `inline-block` display not defined in IE 8/9.
 */ *]]

audio, canvas, video {
	display: inline-block;
}

[[* /**
 * Prevent modern browsers from displaying `audio` without controls.
 * Remove excess height in iOS 5 devices.
 */ *]]

audio:not([controls]) {
	display: none;
	height: 0;
}

[[* /**
 * Address `[hidden]` styling not present in IE 8/9.
 * Hide the `template` element in IE, Safari, and Firefox &lt; 22.
 */ *]]

[hidden], template {
	display: none;
}

[[* /* ==========================================================================
 Base
 ========================================================================== */ *]]

[[* /**
 * 1. Set default font family to sans-serif.
 * 2. Prevent iOS text size adjust after orientation change, without disabling
 *    user zoom.
 */ *]]

html {
	font-family: sans-serif; [[* /* 1 */ *]]
	-ms-text-size-adjust: 100%; [[* /* 2 */ *]]
	-webkit-text-size-adjust: 100%; [[* /* 2 */ *]]
}

[[* /**
 * Remove default margin.
 */ *]]

body {
	margin: 0;
}

[[* /* ==========================================================================
 Links
 ========================================================================== */ *]]

[[* /**
 * Remove the gray background color from active links in IE 10.
 */ *]]

a {
	background: transparent;
}

[[* /**
 * Address `outline` inconsistency between Chrome and other browsers.
 */ *]]

a:focus {
	outline: thin dotted;
}

[[* /**
 * Improve readability when focused and also mouse hovered in all browsers.
 */ *]]

a:active, a:hover {
	outline: 0;
}

[[* /* ==========================================================================
 Typography
 ========================================================================== */ *]]

[[* /**
 * Address variable `h1` font-size and margin within `section` and `article`
 * contexts in Firefox 4+, Safari 5, and Chrome.
 */ *]]

h1 {
	font-size: 2em;
	margin: 0.67em 0;
}

[[* /**
 * Address styling not present in IE 8/9, Safari 5, and Chrome.
 */ *]]

abbr[title] {
	border-bottom: 1px dotted;
}

[[* /**
 * Address style set to `bolder` in Firefox 4+, Safari 5, and Chrome.
 */ *]]

b, strong {
	font-weight: bold;
}

[[* /**
 * Address styling not present in Safari 5 and Chrome.
 */ *]]

dfn {
	font-style: italic;
}

[[* /**
 * Address differences between Firefox and other browsers.
 */ *]]

hr {
	-moz-box-sizing: content-box;
	box-sizing: content-box;
	height: 0;
}

[[* /**
 * Address styling not present in IE 8/9.
 */ *]]

mark {
	background: #ff0;
	color: #000;
}

[[* /**
 * Correct font family set oddly in Safari 5 and Chrome.
 */ *]]

code, kbd, pre, samp {
	font-family: monospace, serif;
	font-size: 1em;
}

[[* /**
 * Improve readability of pre-formatted text in all browsers.
 */ *]]

pre {
	white-space: pre-wrap;
}

[[* /**
 * Set consistent quote types.
 */ *]]

q {
	quotes: "\201C" "\201D" "\2018" "\2019";
}

[[* /**
 * Address inconsistent and variable font size in all browsers.
 */ *]]

small {
	font-size: 80%;
}

[[* /**
 * Prevent `sub` and `sup` affecting `line-height` in all browsers.
 */ *]]

sub, sup {
	font-size: 75%;
	line-height: 0;
	position: relative;
	vertical-align: baseline;
}

sup {
	top: -0.5em;
}

sub {
	bottom: -0.25em;
}

[[* /* ==========================================================================
 Embedded content
 ========================================================================== */ *]]

[[* /**
 * Remove border when inside `a` element in IE 8/9.
 */ *]]

img {
	border: 0;
}

[[* /**
 * Correct overflow displayed oddly in IE 9.
 */ *]]

svg:not(:root) {
	overflow: hidden;
}

[[* /* ==========================================================================
 Figures
 ========================================================================== */ *]]

[[* /**
 * Address margin not present in IE 8/9 and Safari 5.
 */ *]]

figure {
	margin: 0;
}

[[* /* ==========================================================================
 Forms
 ========================================================================== */ *]]

[[* /**
 * Define consistent border, margin, and padding.
 */ *]]

fieldset {
	border: 1px solid #c0c0c0;
	margin: 0 2px;
	padding: 0.35em 0.625em 0.75em;
}

[[* /**
 * 1. Correct `color` not being inherited in IE 8/9.
 * 2. Remove padding so people aren''t caught out if they zero out fieldsets.
 */ *]]

legend {
	border: 0; [[* /* 1 */ *]]
	padding: 0; [[* /* 2 */ *]]
}

[[* /**
 * 1. Correct font family not being inherited in all browsers.
 * 2. Correct font size not being inherited in all browsers.
 * 3. Address margins set differently in Firefox 4+, Safari 5, and Chrome.
 */ *]]

button, input, select, textarea {
	font-family: inherit; [[* /* 1 */ *]]
	font-size: 100%; [[* /* 2 */ *]]
	margin: 0; [[* /* 3 */ *]]
}

[[* /**
 * Address Firefox 4+ setting `line-height` on `input` using `!important` in
 * the UA stylesheet.
 */ *]]

button, input {
	line-height: normal;
}

[[* /**
 * Address inconsistent `text-transform` inheritance for `button` and `select`.
 * All other form control elements do not inherit `text-transform` values.
 * Correct `button` style inheritance in Chrome, Safari 5+, and IE 8+.
 * Correct `select` style inheritance in Firefox 4+ and Opera.
 */ *]]

button, select {
	text-transform: none;
}

[[* /**
 * 1. Avoid the WebKit bug in Android 4.0.* where (2) destroys native `audio`
 *    and `video` controls.
 * 2. Correct inability to style clickable `input` types in iOS.
 * 3. Improve usability and consistency of cursor style between image-type
 *    `input` and others.
 */ *]]

button, html input[type="button"], [[* /* 1 */ *]]
input[type="reset"], input[type="submit"] {
	-webkit-appearance: button; [[* /* 2 */ *]]
	cursor: pointer; [[* /* 3 */ *]]
}

[[* /**
 * Re-set default cursor for disabled elements.
 */ *]]

button[disabled], html input[disabled] {
	cursor: default;
}

[[* /**
 * 1. Address box sizing set to `content-box` in IE 8/9/10.
 * 2. Remove excess padding in IE 8/9/10.
 */ *]]

input[type="checkbox"], input[type="radio"] {
	box-sizing: border-box; [[* /* 1 */ *]]
	padding: 0; [[* /* 2 */ *]]
}

[[* /**
 * 1. Address `appearance` set to `searchfield` in Safari 5 and Chrome.
 * 2. Address `box-sizing` set to `border-box` in Safari 5 and Chrome
 *    (include `-moz` to future-proof).
 */ *]]

input[type="search"] {
	-webkit-appearance: textfield; [[* /* 1 */ *]]
	-moz-box-sizing: content-box;
	-webkit-box-sizing: content-box; [[* /* 2 */ *]]
	box-sizing: content-box;
}

[[* /**
 * Remove inner padding and search cancel button in Safari 5 and Chrome
 * on OS X.
 */ *]]

input[type="search"]::-webkit-search-cancel-button, input[type="search"]::-webkit-search-decoration {
	-webkit-appearance: none;
}

[[* /**
 * Remove inner padding and border in Firefox 4+.
 */ *]]

button::-moz-focus-inner, input::-moz-focus-inner {
	border: 0;
	padding: 0;
}

[[* /**
 * 1. Remove default vertical scrollbar in IE 8/9.
 * 2. Improve readability and alignment in all browsers.
 */ *]]

textarea {
	overflow: auto; [[* /* 1 */ *]]
	vertical-align: top; [[* /* 2 */ *]]
}

[[* /* ==========================================================================
 Tables
 ========================================================================== */ *]]

[[* /**
 * Remove most spacing between table cells.
 */ *]]

table {
	border-collapse: collapse;
	border-spacing: 0;
}

[[* /*! HTML5 Boilerplate v4.3.0 | MIT License | http://h5bp.com/ */ *]]

[[* /*
 * What follows is the result of much research on cross-browser styling.
 * Credit left inline and big thanks to Nicolas Gallagher, Jonathan Neal,
 * Kroc Camen, and the H5BP dev community and team.
 */ *]]

[[* /* ==========================================================================
 Base styles: opinionated defaults
 ========================================================================== */ *]]

html {
	color: #222;
	font-size: 1em;
	line-height: 1.4;
}

[[* /*
 * A better looking default horizontal rule
 */ *]]

hr {
	display: block;
	height: 1px;
	border: 0;
	border-top: 1px solid #ccc;
	margin: 1em 0;
	padding: 0;
}

[[* /*
 * Remove the gap between images, videos, audio and canvas and the bottom of
 * their containers: h5bp.com/i/440
 */ *]]

audio, canvas, img, svg, video {
	vertical-align: middle;
}

[[* /*
 * Remove default fieldset styles.
 */ *]]

fieldset {
	border: 0;
	margin: 0;
	padding: 0;
}

[[* /*
 * Allow only vertical resizing of textareas.
 */ *]]

textarea {
	resize: vertical;
}

[[* /* ==========================================================================
 Helper classes
 ========================================================================== */ *]]

[[* /*
 * Hide from both screenreaders and browsers: h5bp.com/u
 */ *]]

.hidden {
	display: none !important;
	visibility: hidden;
}

[[* /*
 * Hide only visually, but have it available for screenreaders: h5bp.com/v
 */ *]]

.visuallyhidden {
	border: 0;
	clip: rect(0 0 0 0);
	height: 1px;
	margin: -1px;
	overflow: hidden;
	padding: 0;
	position: absolute;
	width: 1px;
}

[[* /*
 * Extends the .visuallyhidden class to allow the element to be focusable
 * when navigated to via the keyboard: h5bp.com/p
 */ *]]

.visuallyhidden.focusable:active, .visuallyhidden.focusable:focus {
	clip: auto;
	height: auto;
	margin: 0;
	overflow: visible;
	position: static;
	width: auto;
}

[[* /*
 * Hide visually and from screenreaders, but maintain layout
 */ *]]

.invisible {
	visibility: hidden;
}

[[* /*
 * Clearfix: contain floats
 *
 * For modern browsers
 * 1. The space content is one way to avoid an Opera bug when the
 *    `contenteditable` attribute is included anywhere else in the document.
 *    Otherwise it causes space to appear at the top and bottom of elements
 *    that receive the `clearfix` class.
 * 2. The use of `table` rather than `block` is only necessary if using
 *    `:before` to contain the top-margins of child elements.
 */ *]]

.cf:before, .cf:after {
	content: " "; [[* /* 1 */ *]]
	display: table; [[* /* 2 */ *]]
}

.cf:after {
	clear: both;
}

[[* /* =====================================
 BASE STYLES
 ===================================== */ *]]

[[* /*
 * 1. Remove default vertical scrollbar in IE6/7/8/9
 * 2. Allow only vertical resizing
 */ *]]
textarea {
	overflow: auto;
	vertical-align: top;
	resize: vertical
}

ul, ol {
	margin: 1em 0;
	padding: 0 0 0 40px
}

dd {
	margin: 0 0 0 40px
}

nav ul, nav ol {
	list-style: none;
	list-style-image: none;
	margin: 0;
	padding: 0
}

[[* /* Redeclare monospace font family */ *]]
pre, code, kbd, samp {
	font-family: monospace, serif;
	_font-family: courier new, monospace;
	font-size: 1em
}

[[* /* Improve readability of pre-formatted text in all browsers */ *]]
pre {
	white-space: pre;
	white-space: pre-wrap;
	word-wrap: break-word
}

q {
	quotes: none
}

q:before, q:after {
	content: "";
	content: none
}

small {
	font-size: 85%
}

[[* /* correct text resizing */ *]]
html {
	font-size: 100%;
	-webkit-text-size-adjust: 100%;
	-ms-text-size-adjust: 100%
}

body {
	margin: 0;
	font-size: 1em;
	-webkit-font-smoothing: antialiased;
}

[[* /* =====================================
 12 COLUMN GRID
 ===================================== */ *]]

[[* /* ==========================================================================
 12 Column Grid System based on the 1140px Grid V2
 by Andy Taylor http://cssgrid.net

 Extended by Goran Ilic http://www.ich-mach-das.at
 https://github.com/Stikki/Yetti/blob/master/static/css/yetti-grid.css
 ========================================================================== */ *]]

.container {
	padding-left: 10px;
	padding-right: 10px;
}

.row {
	width: 100%;
	max-width: 1440px;
	margin: 0 auto;
	position: relative;
}

.row:before, .row:after, .form-row:before, .form-row:after {
	content: " ";
	display: table;
}

.row:after, .form-row:after {
	clear: both;
}

[[* /* ==========================================================================
 Base 12 Column Grid
 ========================================================================== */ *]]

.full {
	width: 100%;
	display: block;
}

.half, .third, .two-third, .quarter, .three-quarter, .fifth, .two-fifth, .three-fifth, .four-fifth {
	float: left;
}

.half {
	width: 50%;
}

.third {
	width: 33.33%;
}

.two-third {
	width: 66.66%;
}

.quarter {
	width: 25%;
}

.three-quarter {
	width: 75%;
}

.fifth {
	width: 20%;
}

.two-fifth {
	width: 40%;
}

.three-fifth {
	width: 60%;
}

.four-fifth {
	width: 80%
}

[[* /* Animate position of columns */ *]]
.row [class*="-col"] {
	-webkit-transition:all .4s ease;
	-moz-transition:all .4s ease;
	-o-transition:all .4s ease;
	-ms-transition:all .4s ease;
	transition:all .4s ease;
}

@media only screen and (min-width: 768px) {

	.container {
		padding-left: 20px;
		padding-right: 20px;
	}

	[[* /* ==========================================================================
	 Base 12 Column Grid
	 ========================================================================== */ *]]

	.col, .one-col, .two-col, .three-col, .four-col, .five-col, .six-col, .seven-col, .eight-col, .nine-col, .ten-col, .eleven-col {
		margin-left: 3.8%;
		float: left;
		min-height: 1px;
		position: relative;
	}
	.row .one-col {
		width: 4.85%;
	}
	.row .two-col {
		width: 13.45%;
	}
	.row .three-col {
		width: 22.05%;
	}
	.row .four-col {
		width: 30.75%;
	}
	.row .five-col {
		width: 39.45%;
	}
	.row .six-col {
		width: 48.1%;
	}
	.row .seven-col {
		width: 56.75%;
	}
	.row .eight-col {
		width: 65.4%;
	}
	.row .nine-col {
		width: 74.05%;
	}
	.row .ten-col {
		width: 82.7%;
	}
	.row .eleven-col {
		width: 91.35%;
	}
	.row .twelve-col {
		width: 100%;
		margin-left: 0;
	}
	.row [class*="-col"]:first-child, .row [class*="-col"].first {
		margin-left: 0;
	}

	[[* /* ==========================================================================
	 Offset Space
	 ========================================================================== */ *]]

	.row .offset-one {
		margin-left: 8.65% !important;
	}
	.row .offset-two {
		margin-left: 17.25% !important;
	}
	.row .offset-three {
		margin-left: 25.85% !important;
	}
	.row .offset-four {
		margin-left: 34.55% !important;
	}
	.row .offset-five {
		margin-left: 43.25% !important;
	}
	.row .offset-six {
		margin-left: 51.8% !important;
	}
	.row .offset-seven {
		margin-left: 60.55% !important;
	}
	.row .offset-eight {
		margin-left: 69.2% !important;
	}
	.row .offset-nine {
		margin-left: 77.85% !important;
	}
	.row .offset-ten {
		margin-left: 86.5% !important;
	}
	.row .offset-eleven {
		margin-left: 95.15% !important;
	}

	[[* /* ==========================================================================
	 Push &amp; Pull Space
	 ========================================================================== */ *]]

	.row .push-one, .row .push-two, .row .push-three, .row .push-four, .row .push-five, .row .push-six, .row .push-seven, .row .push-eight,
	.row .push-nine, .row .push-ten, .row .push-eleven, .row .pull-one, .row .pull-two, .row .pull-three, .row .pull-four, .row .pull-five,
	.row .pull-six, .row .pull-seven, .row .pull-eight, .row .pull-nine, .row .pull-ten, .row .pull-eleven {
		position: relative;
		margin-left: 0;
	}

	.row .push-one {
		left: 8.65%;
	}
	.row .push-two {
		left: 17.25%;
	}
	.row .push-three {
		left: 25.85%;
	}
	.row .push-four {
		left: 34.55%;
	}
	.row .push-five {
		left: 43.25%;
	}
	.row .push-six {
		left: 51.8%;
	}
	.row .push-seven {
		left: 60.55%;
	}
	.row .push-eight {
		left: 69.2%;
	}
	.row .push-nine {
		left: 77.85%;
	}
	.row .push-ten {
		left: 86.5%;
	}
	.row .push-eleven {
		left: 95.15%;
	}

	.row .pull-one {
		right: 4.85%;
	}
	.row .pull-two {
		right: 13.45%;
	}
	.row .pull-three {
		right: 22.05%;
	}
	.row .pull-four {
		right: 30.75%;
	}
	.row .pull-five {
		right: 39.45%;
	}
	.row .pull-six {
		right: 48%;
	}
	.row .pull-seven {
		right: 56.75%;
	}
	.row .pull-eight {
		right: 65.4%;
	}
	.row .pull-nine {
		right: 74.05%;
	}
	.row .pull-ten {
		right: 82.7%;
	}
	.row .pull-eleven {
		right: 91.35%;
	}

}

[[/strip]]]]></content>
		</stylesheet>
		<stylesheet>
			<id>2</id>
			<name>Simplex Layout</name>
			<description>Simplex Theme main layout Stylesheet</description>
			<media_type>screen</media_type>
			<content><![CDATA[[[strip]]

[[* APPEARANCE *]]
[[*
	/**
	 * @copyright CMS Made Simple 2014
	 * @author Goran Ilic (uniqu3e@gmail.com)
	 * @version 1.1 (CMSMS 2.0 Package)
	 *
	 * Simplex Theme comes with 2 predefined Style variations, one is a "boxed" style as seen in
	 * default installation which is controle with "boxed" ID that is set in Simplex Theme &lt;body&gt; tag.
	 * If you remove this ID, a grey background on page body will be removed and layout will no longer
	 * be wrapped inside a "box" but appear in a single background color which is by default white.
	 *
	 * Besides there are also predefined class names and styles that you can use on &lt;body&gt; tag to
	 * change alignment of complete layout/page.
	 * If you rightaligned class to body (example: &lt;body class='rightaligned and other classes'&gt;)
	 * then whole page layout will be positioned to right window side instead of centered position
	 * and with class leftaligned the page layout will be positioned to left.
	 *
	 * Maximum width of page layout is preset to 1440px in Simplex Core stylesheet, you can change this
	 * by adding a new rule in this stylesheet with a class .row (Example: .row { max-width: 1080px; }).
	 * If you prefer a full width layout simply add fullwidth class to body tag of Simplex Template.
	 * This class will reset max-width limitation and force the page layout to full window width with
	 * spacing on left and right of 30px.
	 *
	 * Browser Support:
	 * Simplex Theme was tested in common modern Browser and IE8 (with gracefull fallback).
	 *
	 * Grid usage:
	 * Simplex is using a custom Yetti Framework 12 column grid (https://github.com/Stikki/Yetti/tree/master)
	 * based on Andy Taylors (http://cssgrid.net) 1140px Grid.
	 *
	 * Using the grid system is fairly simple. Make sure that grid columns
	 * are wrapped inside a element with .row class.
	 * When grid columns are inside a row element, floats are auto cleared,
	 * therefore you do not need anything like some empty clear element ie. &lt;div class="clear"&gt;&lt;/div&gt;
	 * Grid columns have a spacing (margin-left) of 3.8% of the layout, whereby first column after
	 * .row opening element will have no spacing (margin-left).
	 * Grid columns are only applied to Browser and Screen size which are greater then 768px;
	 *
	 * Example (three column row):
	 *
	 * &lt;!-- container has a preset padding to left and right with 20px --&gt;
	 * &lt;div class="container"&gt;
	 *     &lt;!-- clears floating row of columns, sets maximum width of 1440px --&gt;
	 *     &lt;div class="row some-class-to-apply-styles"&gt;
	 *         &lt;!--
	 *             four-col explanation: a simple math, grid is built out of 12 columns, so we say we want
	 *             a grid column in size of four columns width therefore the name four- and to fill
	 *             our .row it is three times four-col column makes twelve columns (3 x 4 = 12)
	 *         --&gt;
	 *         &lt;div class="four-col my-class"&gt;
	 *             Some content
	 *         &lt;/div&gt;
	 *         &lt;div class="four-col my-class"&gt;
	 *             Some content
	 *         &lt;/div&gt;
	 *         &lt;div class="four-col my-class"&gt;
	 *             Some content
	 *         &lt;/div&gt;
	 *     &lt;/div&gt;
	 *     &lt;div class="row"&gt;
	 *         &lt;div class="six-col"&gt;
	 *             Half width content
	 *         &lt;/div&gt;
	 *         &lt;div class="six-col"&gt;
	 *             Half width content
	 *         &lt;/div&gt;
	 *     &lt;/div&gt;
	 * &lt;/div&gt;
	 *
	 */
*]]

[[* /* assign the images path to a variable */ *]]
[[capture assign='path']][[uploads_url]]/simplex/images[[/capture]]
[[capture assign='font']][[uploads_url]]/simplex/fonts[[/capture]]

[[* /* --- COLORS --- */ *]]

[[$light_grey='#f1f1f1']]
[[$grey='#e9e9e9']]
[[$dark_grey='#555' scope=global]]
[[$white='#fff']]
[[$off_white='#fefefe']]
[[$orange='#f39c2c' scope=global]]
[[$dark_orange='#e6870e']]
[[$yellow='#fdbd34']]

[[* /* =====================================
 ICON FONT
 ===================================== */ *]]
[[* /* Will fail on Windows Phone 7, sorry developer life sucks */ *]]
@font-face {
	font-family: 'simplex';
	src: url('[[$font]]/simplex.eot');
	src: url('[[$font]]/simplex.eot?#iefix') format('embedded-opentype'),
		url('[[$font]]/simplex.woff') format('woff'),
		url('[[$font]]/simplex.ttf') format('truetype'),
		url('[[$font]]/simplex.svg#simplex') format('svg');
	font-weight: normal;
	font-style: normal;
}

[class^="icon-"], [class*=" icon-"] {
	font-family: 'simplex';
	speak: none;
	font-style: normal;
	font-weight: normal;
	font-variant: normal;
	text-transform: none;
	line-height: 1;
	-webkit-font-smoothing: antialiased;
	-moz-osx-font-smoothing: grayscale;
}

.icon-arrow-up:before {
	content: "\e600";
}

.icon-arrow-left:before {
	content: "\e601";
}

.icon-search:before {
	content: "\e603";
}

.icon-printer:before {
	content: "\e604";
}

.icon-linkedin:before {
	content: "\e605";
}

.icon-pinterest:before {
	content: "\e606";
}

.icon-youtube:before {
	content: "\e607";
}

.icon-facebook:before {
	content: "\e608";
}

.icon-google:before {
	content: "\e609";
}

.icon-twitter:before {
	content: "\e60a";
}

.icon-link:before {
	content: "\e602";
}

[[* /* =====================================
 GENERAL STYLES
 ===================================== */ *]]
body {
	background: [[$white]];
	font-family: 'Noto Sans', sans-serif;
	font-size: 1em; [[* /* base browser font size: 16px, now do math "XX / 16 = ??" where XX is desired font size */ *]]
	color: [[$dark_grey]];
	line-height: 1.5;
}

[[* /* add this class to &lt;body&gt; to align the layout to left instead of centered */ *]]
.leftaligned {
	margin-left: 0;
}

[[* /* add this class to &lt;body&gt; to align the layout to right instead of centered */ *]]
.rightaligned {
	margin-right: 0;
}

[[* /* you can change appearance of the page by adding or removing #boxed id to &lt;body&gt; tag.
 * By removing #boxed ID, page will no longer be wrapped in a wrapper
 */ *]]
body#boxed {
	background: #f2f2f2 url([[$path]]/body-background.png) repeat;
}

[[* /* add this class to &lt;body&gt; to make this layout full window width */ *]]
body.fullwidth .row {
	max-width: none;
}

img {
	max-width: 100%;
}

a img {
	border: none;
}

[[* /* you can use these classes to align images to left or right */ *]]
.right {
	float: right;
}

.left {
	float: left;
}

[[* /* if image needs some space add this class to img tag
 * so at the end a left floating image would be &lt;img src='some.jpg' class='left spacing' alt='foo' /&gt;
 */ *]]
.spacing {
	margin: 15px;
}

.spacing.left {
	margin-right: 0;
}

.spacing.right {
	margin-left: 0;
}

[[* /* or add a 2 px border to image or something, change as you need it */ *]]
.border {
	border: 2px solid [[$grey]];
}

[[* /* some styling for code chunks */ *]]
pre, code, kbd, samp {
	font-family: Consolas, 'Andale Mono WT', 'Andale Mono', 'Lucida Console', 'Lucida Sans Typewriter', monospace;
	color: [[$dark_grey]];
}

pre code {
	line-height: 1.4;
	font-size: .8125em;
}

pre {
	padding: 10px;
	margin: 10px 0;
	overflow: auto;
	width: 93%;
	background: [[$light_grey]];
	border-radius: 6px;
	-webkit-border-radius: 6px;
	-moz-border-radius: 6px;
	-o-border-radius: 6px;
}

[[* /* target IE7 and IE6 */ *]]
*:first-child+ html pre {
	padding-bottom: 20px;
	overflow-y: hidden;
	overflow: visible;
	overflow-x: auto;
}

* html pre {
	padding-bottom: 20px;
	overflow: visible;
	overflow-x: auto;
}

[[* /* horizontal ruler */ *]]
hr {
	border: solid [[$grey]];
	border-width: 1px 0 0 0;
	clear: both;
	margin: 10px 0 30px 0;
	height: 0;
}

[[* /* =====================================
 COMMON TYPOGRAPHY
 ===================================== */ *]]

[[* /* link default styles */ *]]
a {
	color: [[$orange]];
}

a.external {
	text-decoration: none;
}

a:visited {
	color: [[$dark_orange]];
}

a:hover {
	color: [[$dark_grey]];
	transition: transform .3s ease-out;
	-webkit-transition: color .3s ease-out;
	-moz-transition: color .3s ease-out;
	-o-transition: color .3s ease-out;
	text-decoration: underline;
}

a:focus {
	outline: thin dotted;
}

a:hover, a:active {
	outline: 0;
}

[[* /* add icon to links with class external */ *]]
a.external:after {
	content: "\e602";
	padding-left: 4px;
	font-family: 'simplex';
	text-decoration: none;
}

[[* /* default heading styles */ *]]
h1, h2 {
	font-family: 'Oswald', Impact, Haettenschweiler, 'Arial Narrow Bold', sans-serif;
	font-weight: 700;
}

h3, h4, h5, h6 {
	font-weight: 400;
}

h1 {
	color: [[$orange]];
	margin: 10px 0;
	font-size: 2em; [[* /* 32px */ *]]
	text-transform: uppercase;
}

h2 {
	color: [[$dark_grey]];
	font-size: 1.75em; [[* /* 28px */ *]]
}

h3 {
	color: [[$dark_grey]];
	font-size: 1.5em; [[* /* 24px */ *]]
}

h4 {
	color: [[$orange]];
	font-size: 1.375em; [[* /* 22px */ *]]
}

h5 {
	font-size: 1.25em [[* /* 20px */ *]]
}

h6 {
	font-size: 1.125em; [[* /* 18px */ *]]
}

[[* /* blockquotes and cites */ *]]
blockquote, blockquote p {
	font-size: 1.0625em;
	line-height: 1.5;
	color: [[$dark_grey]];
	font-style: italic;
	font-family: Georgia, Times New Roman, serif;
}

blockquote {
	margin: 0 0 20px 0;
	padding: 9px 10px 10px 19px;
	border-left: 5px solid [[$light_grey]];
}

blockquote cite {
	display: block;
	font-size: .941176em;
	color: [[$dark_grey]];
}

blockquote cite:before {
	content: "\2014 \0020";
}

blockquote cite a, blockquote cite a:visited, blockquote cite a:visited {
	font-family: Georgia, Times New Roman, serif;
}

[[* /* =====================================
 LAYOUT
 ===================================== */ *]]