<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE cmsmsinstall [
 <!ELEMENT dtdversion (#PCDATA)>
 <!ELEMENT designs (design+)>
 <!ELEMENT design (id,name,description?,dflt?)>
 <!ELEMENT id (#PCDATA)>
 <!ELEMENT name (#PCDATA)>
 <!ELEMENT description (#PCDATA)>
 <!ELEMENT dflt (#PCDATA)>
 <!ELEMENT tpltypes (tpltype+)>
 <!ELEMENT tpltype (id,name,description?,originator,one_only?,has_dflt?,dflt_contents?,requires_contentblocks?,lang_cb?,dflt_content_cb?,help_content_cb?)>
 <!ELEMENT originator (#PCDATA)>
 <!ELEMENT one_only (#PCDATA)>
 <!ELEMENT has_dflt (#PCDATA)>
 <!ELEMENT dflt_contents (#PCDATA)>
 <!ELEMENT requires_contentblocks (#PCDATA)>
 <!ELEMENT lang_cb (#PCDATA)>
 <!ELEMENT dflt_content_cb (#PCDATA)>
 <!ELEMENT help_content_cb (#PCDATA)>
 <!ELEMENT templates (template)>
 <!ELEMENT template (id,name,description?,type_id,category_id?,type_dflt?,content)>
 <!ELEMENT type_id (#PCDATA)>
 <!ELEMENT type_dflt (#PCDATA)>
 <!ELEMENT content (#PCDATA)>
 <!ELEMENT pages (page+)>
 <!ELEMENT page (content_id,content_name,content_alias?,type,template_id,parent_id,active?,default_content?,show_in_menu?,menu_text?,cachable?)>
 <!ELEMENT content_id (#PCDATA)>
 <!ELEMENT content_name (#PCDATA)>
 <!ELEMENT content_alias (#PCDATA)>
 <!ELEMENT type (#PCDATA)>
 <!ELEMENT template_id (#PCDATA)>
 <!ELEMENT parent_id (#PCDATA)>
 <!ELEMENT active (#PCDATA)>
 <!ELEMENT default_content (#PCDATA)>
 <!ELEMENT show_in_menu (#PCDATA)>
 <!ELEMENT menu_text (#PCDATA)>
 <!ELEMENT cacheable (#PCDATA)>
 <!ELEMENT properties (property+)>
 <!ELEMENT property (content_id,prop_name,content)>
 <!ELEMENT prop_name (#PCDATA)>
]>
<cmsmsinstall>
	<dtdversion>0.6</dtdversion>
	<designs>
		<design>
			<id>1</id>
			<name>Default</name>
			<description>Default design with just the default template</description>
			<dflt>1</dflt>
		</design>
	</designs>
	<tpltypes>
		<tpltype>
			<id>1</id>
			<name>page</name>
			<originator>__CORE__</originator>
			<lang_cb>\CMSMS\internal\std_layout_template_callbacks::page_type_lang_callback</lang_cb>
			<dflt_content_cb>\CMSMS\internal\std_layout_template_callbacks::reset_page_type_defaults</dflt_content_cb>
			<help_content_cb>\CMSMS\internal\std_layout_template_callbacks::template_help_callback</help_content_cb>
		</tpltype>
		<tpltype>
			<id>2</id>
			<name>generic</name>
			<originator>__CORE__</originator>
			<lang_cb>\CMSMS\internal\std_layout_template_callbacks::generic_type_lang_callback</lang_cb>
			<help_content_cb>\CMSMS\internal\std_layout_template_callbacks::template_help_callback</help_content_cb>
		</tpltype>
	</tpltypes>
	<templates>
		<template>
			<id>1</id>
			<name>Default</name>
			<description>A simple starting point to build templates from</description>
			<type_id>1</type_id>
			<type_dflt>1</type_dflt>
			<content><![CDATA[{strip} {process_pagedata} {/strip}
&lt;!doctype html&gt;
&lt;html lang="{cms_get_language}"&gt;
&lt;head&gt;
  &lt;title&gt;{title} - {sitename}&lt;/title&gt;
  {metadata}
  {cms_stylesheet}
&lt;/head&gt;
&lt;body&gt;
  &lt;header id="header"&gt;
    &lt;h1&gt;{sitename}&lt;/h1&gt;
  &lt;/header&gt;

  &lt;nav id="menu"&gt;
    {Navigator}
  &lt;/nav&gt;

  &lt;section id="content"&gt;
    &lt;h1&gt;{title}&lt;/h1&gt;
    {content}
  &lt;/section&gt;
&lt;/body&gt;
&lt;/html&gt;]]></content>
		</template>
	</templates>
	<pages>
		<page>
			<content_id>1</content_id>
			<content_name>Home</content_name>
			<content_alias>home</content_alias>
			<type>content</type>
			<template_id>1</template_id>
			<parent_id>-1</parent_id>
			<active>1</active>
			<default_content>1</default_content>
			<show_in_menu>1</show_in_menu>
			<menu_text><![CDATA[Home]]></menu_text>
			<cachable>1</cachable>
		</page>
	</pages>
	<properties>
		<property>
			<content_id>1</content_id>
			<prop_name>searchable</prop_name>
			<content><![CDATA[1]]></content>
		</property>
		<property>
			<content_id>1</content_id>
			<prop_name>design_id</prop_name>
			<content><![CDATA[1]]></content>
		</property>
		<property>
			<content_id>1</content_id>
			<prop_name>content_en</prop_name>
			<content><![CDATA[&lt;p&gt;Congratulations! The installation worked. You now have a fully functional installation of CMS Made Simple and you are &lt;em&gt;almost&lt;/em&gt; ready to start building your site.&lt;/p&gt;&lt;p&gt;If you chose to install the default content, you will see numerous pages available to read.  You should read them thoroughly  as these default pages are devoted to showing you the basics of how to begin working with CMS Made Simple.  On these example pages, templates, and stylesheets many of the features of the default installation of CMS Made Simple are described and demonstrated. You can learn much about the power of CMS Made Simple by absorbing this information.&lt;/p&gt;&lt;p&gt;To get to the Administration Console you have to login as the administrator (with the username/password you mentioned during the installation process) on your site at http://yourwebsite.com/cmsmspath/admin.  If this is your site click &lt;a title="CMSMS Demo Admin Panel" href="admin"&gt;here&lt;/a&gt; to login.&lt;/p&gt;&lt;p&gt;Read about how to use CMS Made Simple in the &lt;a class="external" href="http://docs.cmsmadesimple.org/" title="CMS Made Simple Documentation" target="_blank"&gt;documentation&lt;/a&gt;. In case you need any help the community is always at your service, in the  &lt;a class="external" href="http://forum.cmsmadesimple.org" title="CMS Made Simple Forum" target="_blank"&gt;forum&lt;/a&gt; or the &lt;a class="external" href="http://www.cmsmadesimple.org/support/irc" title="Information about the CMS Made Simple IRC channel" target="_blank"&gt;IRC&lt;/a&gt;.&lt;/p&gt;&lt;h3&gt;License&lt;/h3&gt;&lt;p&gt;CMS Made Simple is released under the &lt;a class="external" href="http://www.gnu.org/licenses/licenses.html#GPL" title="General Public License" target="_blank"&gt;GPL&lt;/a&gt; license and as such you don't have to leave a link back to us in these templates or on your site as much as we would like it.&lt;/p&gt;&lt;p&gt; Some third party add-on modules may include additional license restrictions.&lt;/p&gt;]]></content>
		</property>
	</properties>
</cmsmsinstall>
